### ISSUE TITLE
Fatal error with hexo 3 ?

### ISSUE THREAD

**Issue by xoox** [hexojs/hexo-generator-alias#1]
This plugin seems failed with hexo 3. Here goes the testing.

``` sh
$ hexo init testalias
$ cd testalias
$ npm install
$ npm install hexo-generator-alias --save
$ hexo s
```

Then you get `FATAL Something's wrong`.

```
TypeError: undefined is not a function
...
```

**Comment by tommy351** [comment]
hexo-generator-alias is not compatible with Hexo 3 so far.

**Comment by joezimjs** [comment]
Is there a plan to change that soon? In the meantime, I think there should at least be a warning on the README that it isn't compatible.

**Comment by joezimjs** [comment]
Can you verify that commit 342e2cead649b0df84201b2a06fbed824f0cb8d7 solves this issue?

**Comment by xoox** [comment]
Hi, Thank your great job, @joezimjs 
I've tested the new one. It works.
But @tommy351 did not publish it to the npm registry yet.

**Comment by sergiolepore** [comment]
+1

**Comment by s10wen** [comment]
I tried this from npm, but also had errors, so I updated the `index.js` from https://github.com/hexojs/hexo-generator-alias/commit/342e2cead649b0df84201b2a06fbed824f0cb8d7 and this stops the error, but I still haven't managed to get it to work.

I'm trying to update any links that include `/blog/categories/` to redirect to `/categories/`.

I've tried adding a few things to my `_config.yml` but no joy so far. Any ideas please?

**Comment by philippkeller** [comment]
I too would like this to be made hexo 3 compatible, I now have broken links because of that

**Comment by fabianmarz** [comment]
:+1:

**Comment by laurentkempe** [comment]
You can also install it directly from github repo with the following command

    npm install git+https://github.com/hexojs/hexo-generator-alias.git --save

And then it works with Hexo 3.0

**Comment by curbengh** [comment]
hexo 3 has been deprecated, please use hexo 5+.
